/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package riansyah.unikom.skripsitrapende.gui;

/**
 *
 * @author CHAMONZ
 */
public class PanelStatistika extends javax.swing.JPanel {

    /**
     * Creates new form PanelLaporan
     */
    public PanelStatistika() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnButton = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnKwn = new javax.swing.JButton();
        btnAgama = new javax.swing.JButton();
        btnUmur = new javax.swing.JButton();
        btnProfesi = new javax.swing.JButton();
        btnPendidikan = new javax.swing.JButton();
        panelDinamic = new javax.swing.JPanel();
        panelBackground = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        btnButton.setBackground(new java.awt.Color(56, 181, 74));
        btnButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporticon.png"))); // NOI18N
        btnRegister.setText("Register");
        btnRegister.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnKwn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporticon.png"))); // NOI18N
        btnKwn.setText("Kewarganegaraan");
        btnKwn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKwn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKwnActionPerformed(evt);
            }
        });

        btnAgama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporticon.png"))); // NOI18N
        btnAgama.setText("Agama");
        btnAgama.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgamaActionPerformed(evt);
            }
        });

        btnUmur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporticon.png"))); // NOI18N
        btnUmur.setText("Umur");
        btnUmur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUmur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmurActionPerformed(evt);
            }
        });

        btnProfesi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporticon.png"))); // NOI18N
        btnProfesi.setText("Profesi");
        btnProfesi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfesi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProfesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesiActionPerformed(evt);
            }
        });

        btnPendidikan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporticon.png"))); // NOI18N
        btnPendidikan.setText("Pendidikan");
        btnPendidikan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPendidikan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPendidikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendidikanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnButtonLayout = new javax.swing.GroupLayout(btnButton);
        btnButton.setLayout(btnButtonLayout);
        btnButtonLayout.setHorizontalGroup(
            btnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKwn, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(btnAgama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUmur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPendidikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnButtonLayout.setVerticalGroup(
            btnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKwn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfesi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDinamic.setBackground(new java.awt.Color(153, 255, 153));
        panelDinamic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));
        panelDinamic.setLayout(new java.awt.CardLayout());

        panelBackground.setBackground(new java.awt.Color(56, 181, 74));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgicon2.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("STATISTIKA PENDUDUK");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(101, 101, 101)
                .addComponent(jLabel4))
        );

        panelDinamic.add(panelBackground, "card2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("..::STATISTIKA PENDUDUK::..");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDinamic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDinamic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        PanelLaporanRegister panelLaporanRegister = new PanelLaporanRegister();
        panelDinamic.removeAll();
        panelDinamic.add(panelLaporanRegister);
        panelDinamic.repaint();
        panelDinamic.revalidate();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnKwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKwnActionPerformed
        PanelLaporanKewarganegaraan panelLaporanKewarganegaraan = new PanelLaporanKewarganegaraan();
        panelDinamic.removeAll();
        panelDinamic.add(panelLaporanKewarganegaraan);
        panelDinamic.repaint();
        panelDinamic.revalidate();
    }//GEN-LAST:event_btnKwnActionPerformed

    private void btnAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgamaActionPerformed
        PanelLaporanAgama panelLaporanAgama = new PanelLaporanAgama();
        panelDinamic.removeAll();
        panelDinamic.add(panelLaporanAgama);
        panelDinamic.repaint();
        panelDinamic.revalidate();
    }//GEN-LAST:event_btnAgamaActionPerformed

    private void btnUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmurActionPerformed
        PanelLaporanUmur panelLaporanUmur = new PanelLaporanUmur();
        panelDinamic.removeAll();
        panelDinamic.add(panelLaporanUmur);
        panelDinamic.repaint();
        panelDinamic.revalidate();
    }//GEN-LAST:event_btnUmurActionPerformed

    private void btnPendidikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendidikanActionPerformed
        PanelLaporanPendidikan panelLaporanPendidikan = new PanelLaporanPendidikan();
        panelDinamic.removeAll();
        panelDinamic.add(panelLaporanPendidikan);
        panelDinamic.repaint();
        panelDinamic.revalidate();
    }//GEN-LAST:event_btnPendidikanActionPerformed

    private void btnProfesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesiActionPerformed
        PanelLaporanProfesi panelLaporanProfesi = new PanelLaporanProfesi();
        panelDinamic.removeAll();
        panelDinamic.add(panelLaporanProfesi);
        panelDinamic.repaint();
        panelDinamic.revalidate();
    }//GEN-LAST:event_btnProfesiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgama;
    private javax.swing.JPanel btnButton;
    private javax.swing.JButton btnKwn;
    private javax.swing.JButton btnPendidikan;
    private javax.swing.JButton btnProfesi;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUmur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelDinamic;
    // End of variables declaration//GEN-END:variables
}
